export { default as Header } from "./header";
export { default as Footer } from "./footer";
export { default as LazyLoad } from "./lazyLoadImg/Img";
export { default as ContentWrapper } from "./contentWrapper/ContentWrapper";
export { default as SwitchTabs } from "./switchTab/SwitchTabs";
export { default as Carousel } from "./carousel/Carousel";
export { default as Rating } from "./ratings/Ratings";
export { default as Genres } from "./genres/Genres";
export { default as VideoPopup } from "./videoPopup/VideoPopup";
