name: Issue labeler

on:
  issues:
    types: [opened]

jobs:
  label-issues-policy:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    strategy:
      matrix:
        template: ['bug_report.yml']

    steps:
      - uses: actions/checkout@v3

      - name: Add label 'GSSoC2023'
        run: |
          gh issue label add ${{ github.repository }} ${{ github.event.issue.number }} GSSoC2023
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
