name: Issue labeler

on:
  issues:
    types: [opened]

jobs:
  label-issues-policy:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    strategy:
      matrix:
        template: ['bug_report.yml']

    steps:
      - uses: actions/checkout@v3

      - name: Set labels based on policy
        uses: redhat-plumbers-in-action/advanced-issue-labeler@main
        with:
          template: ${{ matrix.template }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add label 'GSSoC2023'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const repo = context.repo.owner + '/' + context.repo.repo;
            const label = 'GSSoC2023';

            const addLabelParams = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: [label]
            };

            await github.issues.addLabels(addLabelParams);
